#!/bin/sh
# install in initramfs-tools/hooks/luksipc

set -e

PREREQ=""

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_file config /etc/initramfs-tools/support/mtools.conf /etc
copy_exec /sbin/cryptsetup
copy_exec /sbin/dmsetup
copy_exec /lib/cryptsetup/askpass
copy_exec /usr/sbin/cryptsetup-reencrypt || true
copy_exec /bin/mktemp
# mtools dynamically loads this one, ow.
copy_file library /usr/lib/$(dpkg-architecture -qDEB_BUILD_MULTIARCH)/gconv/IBM850.so /usr/lib/$(dpkg-architecture -qDEB_BUILD_MULTIARCH)/gconv/IBM850.so
copy_file library /usr/lib/$(dpkg-architecture -qDEB_BUILD_MULTIARCH)/gconv/gconv-modules /usr/lib/$(dpkg-architecture -qDEB_BUILD_MULTIARCH)/gconv/gconv-modules
# EXTRA POINTS to armbian for this shit
copy_file library /usr/lib/$(dpkg-architecture -qDEB_BUILD_MULTIARCH)/gconv/gconv-modules.d/gconv-modules-extra.conf /usr/lib/$(dpkg-architecture -qDEB_BUILD_MULTIARCH)/gconv/gconv-modules.d/gconv-modules-extra.conf || true
copy_exec /sbin/blkid /sbin
copy_exec /bin/lsblk /bin
copy_exec /usr/bin/mcopy /usr/bin
copy_exec /usr/sbin/e2fsck /sbin
copy_exec /usr/sbin/tune2fs /sbin
copy_exec /usr/sbin/resize2fs
# for cryptsetup-reencrypt
copy_file library /usr/lib/$(dpkg-architecture -qDEB_BUILD_MULTIARCH)/libgcc_s.so.1 || true
copy_exec /usr/bin/date
copy_exec /usr/bin/od
copy_exec /usr/bin/dd
copy_exec /usr/bin/expr
copy_exec /usr/bin/echo
copy_exec /usr/bin/grep
copy_exec /usr/bin/cat
copy_exec /usr/bin/rm
copy_exec /usr/bin/xargs
copy_exec /usr/sbin/sfdisk
copy_exec /usr/bin/readlink
copy_exec /usr/bin/basename
copy_exec /usr/bin/sed

manual_add_modules aes
manual_add_modules sha256
manual_add_modules dm_crypt
