#!/bin/sh
# install in initramfs-tools/hooks/resize-parttbl

set -e

PREREQ=""

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/awk /usr/bin
copy_exec /sbin/blkid /sbin
copy_exec /bin/lsblk /bin
copy_exec /sbin/parted /sbin
