#!/usr/bin/env bash

set -e

case "${RPI_INITRD}" in
  Y*|y*|T*|t*|1) : ;;
  *)             exit 0 ;;
esac

# expects args like this - "5.4.51-v7l+" "/boot/kernel7l.img"
initrdpath="${2/kernel/initrd}"
mkinitramfs -o "${initrdpath}" "${1}"
