#!/usr/bin/env bash

# this is a hook to extract the <nut> block from IMD and save under /run/untrustedhost/nut/conf.xml
mkdir -p /run/untrustedhost/nut
touch /run/untrustedhost/nut/conf.xml
chmod 0600 /run/untrustedhost/nut/conf.xml
xmlstarlet sel -t -c metadata/nut "${IMD_PATH}" > /run/untrustedhost/nut/conf.xml

# always return ok though - it's ok :)
exit 0
