#!/usr/bin/env bash

# unfortunately, we can't rotate the screen by this point, but we can set it
# for the _next_ boot.

# extracted from initonce.
imd_rot="$(xmlstarlet sel -t -v 'metadata/raspberrypi/screen/@rotation' '/boot/IMD/MDDATA.XML')"
case "${imd_rot}" in
  0)   pi_rot=0 ;;
  90)  pi_rot=1 ;;
  180) pi_rot=2 ;;
  270) pi_rot=3 ;;
  *)   :        ;;
esac
[ "${pi_rot}" ] && {
  # shellcheck disable=SC2016
  sed -i -e '/^\(lcd_rotate=\).*/{s//\1'"${pi_rot}"'/;:a;n;ba;q}' -e '$alcd_rotate='"${pi_rot}" '/boot/config.txt'
}

exit 0
