#!/usr/bin/env bash

# walk /etc/untrustedhost/netxml and create bird config statements for interfaces.
# shellcheck source=../shellib/imd.bash
. /usr/lib/untrustedhost/shellib/imd.bash

for f in /etc/untrustedhost/netxml/*.xml ; do
  [[ -f "${f}" ]] || { err 'failed to find any netxml' ; exit 1 ; }
  prefix="$(basename "$f" .xml)"
  conf="/etc/anycast-healthchecker.d/${prefix}.conf"
  addrs=$(getaddrsv4 "${prefix}")
  grep -qF "interface = ${prefix}.0" "${conf}" || printf 'interface = %s.0\n' "${prefix}" >> "${conf}"
  for a in ${addrs} ; do
    grep -qF "ip_prefix = ${a}" "${conf}" || printf 'ip_prefix = %s\n' "${a}" >> "${conf}"
  done
done
