#!/usr/bin/env bash

# walk /etc/untrustedhost/netxml and create bird config statements for interfaces.

# shellcheck source=../shellib/imd.bash
. /usr/lib/untrustedhost/shellib/imd.bash

addrs=()
prefixes=()
pinfix=1

for f in /etc/untrustedhost/netxml/*.xml ; do
  # if this resolved to '*' leave now.
  [[ -f "${f}" ]] || { err 'failed to find any netxml' ; exit 1 ; }
  prefix="$(basename "$f" .xml)"
  prefixes=("${prefix}" "${prefixes[@]}")
  addrs=($(getaddrsv4 "${prefix}") "${addrs[@]}")
done

{
# filter out prefixes _we_ have from other hosts
cat <<EOF
function avoid_selfadv()
prefix set selfslice;
{
  selfslice = [ ${addrs[*]} ];
  if net ~ selfslice then return false;
  return true;
}
EOF

for prefix in "${prefixes[@]}" ; do
cat <<EOF
protocol direct direct${pinfix} {
  interface "${prefix}.0";
  export none;
  import all;
}
EOF
pinfix=$((pinfix + 1))
done
} > /etc/bird/anycast-interfaces.conf
