#!/bin/sh
# install in initramfs-tools/hooks/ld-preload-hack

set -e

PREREQ=""

prereqs () {
	echo "\${PREREQ}"
}

case "\${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /bin/mount /bin
copy_exec /bin/mv /bin
